---
title: "Gettin_Started_with_cellmigRation"
output:
  html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Gettin_Started_with_cellmigRation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", echo = TRUE, include = TRUE, eval = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center", fig.keep = "last", fig.height = 5,
  fig.width = 9
)
```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 14)
```

```{r setup, include=FALSE, eval=TRUE}
library(ggplot2)
library(dplyr)
library(cellmigRation)
library(grid)

data("ThreeConditions")
LS <- ThreeConditions

```

### Introduction

```{r}
LS[[1]]
```



```{r}
x0 <- cellmigRation::TrackCellsDataset
x0 <- setCellsMeta(x0, experiment = "my_exp_01", condition = "CTRL")
x1 <- setCellsMeta(x0, experiment = "my_exp_01", condition = "DMSO")
x2 <- setCellsMeta(x0, experiment = "my_exp_01", condition = "DRUG")
y <- aggregateTrackedCells(x0, x1, x2, meta_id_field = "condition")
y[1:40, ]
```


